# Generated by Django 4.2.1 on 2023-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='icon',
            field=models.CharField(blank=True, help_text='Humanitarian Icon', max_length=100, null=True),
        ),
    ]
